/**
 * @openelement/adapter-vite — #1160 TSX-to-Part Program vertical compiler spike.
 *
 * Behavior-first coverage for the open:compiled-element spike transform:
 *   - the one-component fixture is transformed through the actual Vite plugin
 *     transform hook registered by createOpenPlugin()
 *   - the emitted module embeds one deterministic, serializable Part Program
 *     (static structure + typed Part/Region instructions) that deep-equals the
 *     frozen expected-program.json fixture consumed by the element runtime test
 *   - re-running the transform yields byte-identical output
 *   - unsupported syntax fails closed at transform time with a source-located
 *     diagnostic; no runtime fallback is emitted
 *   - measurement evidence (generated bytes, instruction count) is recorded
 *
 * The compiler modules are loaded via dynamic import so a RED run proves the
 * harness and fixtures work while the new vertical behavior is absent.
 */

import { assert, assertEquals, assertStringIncludes, assertThrows } from '@std/assert';
import { createOpenPlugin } from '../src/plugin.ts';
import type { Plugin } from 'vite';

const FIXTURE_DIR = new URL('../__fixtures__/compiled-element-spike/', import.meta.url);

async function readFixture(name: string): Promise<string> {
  return await Deno.readTextFile(new URL(name, FIXTURE_DIR));
}

type PluginModule = typeof import('../src/internal/compiler/plugin.ts');

async function loadPluginModule(): Promise<PluginModule> {
  return await import('../src/internal/compiler/plugin.ts');
}

interface TransformContext {
  error(message: string): never;
}

function failingContext(): TransformContext & { messages: string[] } {
  const messages: string[] = [];
  return {
    messages,
    error(message: string): never {
      messages.push(message);
      throw new Error(message);
    },
  };
}

type TransformHook = (this: TransformContext, code: string, id: string) => string | null;

function transformOf(plugin: Plugin): TransformHook {
  assert(typeof plugin.transform === 'function', 'plugin must expose a transform hook');
  return plugin.transform as unknown as TransformHook;
}

Deno.test('compiled-element spike - harness sanity (fixtures load)', async () => {
  const counter = await readFixture('counter.tsx');
  const expected = await readFixture('expected-program.json');
  assert(counter.includes("@element('oe-spike-counter')"));
  assertEquals(JSON.parse(expected).tag, 'oe-spike-counter');
});

Deno.test('compiled-element spike - plugin registration through createOpenPlugin', async (t) => {
  await t.step('default pipeline does not register the spike compiler', () => {
    const plugins = createOpenPlugin();
    assertEquals(plugins.some((p) => p.name === 'open:compiled-element'), false);
  });

  await t.step('opt-in spike flag registers the compiler plugin', async () => {
    // Behavior-first ordering (repair-1, R3): the pipeline assertion runs
    // BEFORE the new compiler module is imported, so on a base-SHA checkout
    // this step fails because the opt-in pipeline lacks the plugin — not
    // because a module cannot be resolved. The cast keeps the RED-authored
    // test compiling against the not-yet-widened signature.
    const spikeOptions = { compiledSpike: true } as unknown as Parameters<
      typeof createOpenPlugin
    >[0];
    const plugins = createOpenPlugin(spikeOptions);
    assertEquals(plugins.some((p) => p.name === 'open:compiled-element'), true);
    const { compiledElementPlugin } = await loadPluginModule();
    assertEquals(compiledElementPlugin().name, 'open:compiled-element');
  });
});

Deno.test('compiled-element spike - fixture transforms through the Vite hook', async (t) => {
  const { compiledElementPlugin } = await loadPluginModule();
  const plugin = compiledElementPlugin();
  const transform = transformOf(plugin);
  const source = await readFixture('counter.tsx');
  const id = '/project/app/islands/counter.tsx';

  let emitted: string | null = null;
  await t.step('transform returns generated code', () => {
    emitted = transform.call(failingContext(), source, id);
    assert(typeof emitted === 'string');
    assertStringIncludes(emitted, '__partProgram');
  });

  const programLiteral = (code: string): string => {
    const marker = 'const __partProgram = ';
    const start = code.indexOf(marker);
    assert(start >= 0, 'generated code must embed the Part Program literal');
    const end = code.indexOf(';', start);
    return code.slice(start + marker.length, end);
  };

  await t.step('emitted program deep-equals the frozen expected program', async () => {
    const expected = JSON.parse(await readFixture('expected-program.json'));
    assertEquals(JSON.parse(programLiteral(emitted!)), expected);
  });

  await t.step('emitted metadata preserves @property reflection decisions (R2)', () => {
    const marker = 'const __compiledProperties = ';
    const start = emitted!.indexOf(marker);
    assert(start >= 0, 'generated code must embed compiled-property metadata');
    const end = emitted!.indexOf(';', start);
    const metadata = JSON.parse(emitted!.slice(start + marker.length, end));
    // Exact fixture decisions: count reflected; label and items not reflected.
    assertEquals(metadata, [
      {
        name: 'count',
        attribute: 'count',
        type: 'number',
        converter: 'number',
        reflect: true,
        default: 0,
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string',
        converter: 'string',
        reflect: false,
        default: 'ready',
      },
      {
        name: 'items',
        attribute: 'items',
        type: 'array',
        converter: 'array',
        reflect: false,
        default: [
          { id: 'a', text: 'alpha' },
          { id: 'b', text: 'beta' },
        ],
      },
    ]);
    // Compile-time data only: no runtime reflection behavior is emitted.
    assertEquals(emitted!.includes('attributeChangedCallback'), false);
    assertStringIncludes(emitted!, 'static __compiledProperties = __compiledProperties;');
    assertStringIncludes(emitted!, 'static props = __compiledProps;');
    assertStringIncludes(emitted!, 'static observedAttributes = __observedAttributes;');
  });

  await t.step('program carries static structure plus typed Part/Region instructions', () => {
    const program = JSON.parse(programLiteral(emitted!));
    assertEquals(program.version, 1);
    const kinds = program.parts.map((p: { k: string }) => p.k).sort();
    assertEquals(kinds, ['each', 'event', 'prop', 'text', 'when']);
    // instruction count = typed parts; static structure lives in the template
    assertEquals(program.parts.length, 5);
  });

  await t.step('emitted code contains no VNode/binding/hydration fallback vocabulary', () => {
    for (
      const token of [
        'VNode',
        'BindingDescriptor',
        'hydrationScope',
        'HydrationScope',
        'createElement(',
      ]
    ) {
      assertEquals(emitted!.includes(token), false, `generated code must not contain ${token}`);
    }
    assertStringIncludes(emitted!, 'not available in 0.44');
  });

  await t.step('re-running the transform yields byte-identical output', () => {
    const again = transform.call(failingContext(), source, id);
    assertEquals(again, emitted);
  });

  await t.step('measurement evidence is recorded', () => {
    const programJson = programLiteral(emitted!);
    const generatedBytes = new TextEncoder().encode(emitted!).length;
    const programBytes = new TextEncoder().encode(programJson).length;
    const instructionCount = JSON.parse(programJson).parts.length;
    // Frozen spike evidence (alpha.0 fixture): regenerated only by changing the
    // fixture grammar. These are evidence, not a performance claim.
    assertEquals(instructionCount, 5);
    console.log(
      JSON.stringify({
        spike: 'adapter-compiler',
        generatedBytes,
        programBytes,
        instructionCount,
      }),
    );
  });

  await t.step('files outside the spike grammar marker pass through untouched', () => {
    const result = transform.call(
      failingContext(),
      'export class Plain { render() { return null; } }',
      '/project/app/components/plain.tsx',
    );
    assertEquals(result, null);
  });
});

Deno.test('compiled-element spike - unsupported syntax fails closed with located diagnostics', async (t) => {
  const { compiledElementPlugin } = await loadPluginModule();
  const transform = transformOf(compiledElementPlugin());

  await t.step('spread attributes are rejected with file/line location', async () => {
    const source = await readFixture('unsupported-spread.tsx');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/unsupported-spread.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for unsupported syntax');
    assertEquals(ctx.messages.length, 1);
    const message = ctx.messages[0];
    assertStringIncludes(message, 'unsupported-spread.tsx:');
    assertStringIncludes(message, 'OEC9');
    assertStringIncludes(message.toLowerCase(), 'spread');
  });

  await t.step('unknown decorators on an OpenElement class fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function mystery(): ClassDecorator;',
      "@element('oe-spike-mystery')",
      '@mystery()',
      'export class Mystery extends OpenElement {',
      '  render() { return <div>ok</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/mystery.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for unknown decorators');
    assertStringIncludes(ctx.messages[0], 'mystery.tsx:');
    assertStringIncludes(ctx.messages[0].toLowerCase(), 'decorator');
  });

  await t.step('classes not extending OpenElement fail closed', () => {
    const source = [
      'declare function element(tag: string): ClassDecorator;',
      "@element('oe-spike-alien')",
      'export class Alien extends HTMLElement {',
      '  render() { return null; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/alien.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for non-OpenElement base classes');
    assertStringIncludes(ctx.messages[0], 'OpenElement');
  });

  await t.step('path-addressed fixed sinks after dynamic anchors fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function property(options: { reflect: boolean }): PropertyDecorator;',
      "@element('oe-spike-unsafe-path')",
      'export class UnsafePath extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() {',
      '    return <div>{this.count > 0 ? <p>positive</p> : <p>zero</p>}<input value={this.label} /></div>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-path.tsx'),
      Error,
      'OEC9015',
    );
    assertStringIncludes(ctx.messages[0], 'dynamic anchor');
  });

  await t.step('duplicate static and dynamic attribute sinks fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function property(options: { reflect: boolean }): PropertyDecorator;',
      "@element('oe-spike-duplicate-attribute')",
      'export class DuplicateAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input value="static" value={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/duplicate-attribute.tsx'),
      Error,
      'duplicate attribute',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9011');
  });

  await t.step('void elements with children fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      "@element('oe-spike-void-children')",
      'export class VoidChildren extends OpenElement {',
      '  render() { return <input>not supported</input>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/void-children.tsx'),
      Error,
      'void element',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9013');
  });

  await t.step('event-looking attribute sinks fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function property(options: { reflect: boolean }): PropertyDecorator;',
      "@element('oe-spike-unsafe-attribute')",
      'export class UnsafeAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input onclick={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-attribute.tsx'),
      Error,
      'unsafe',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9011');
  });

  await t.step('conditions outside the seed operator fail closed', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function property(options: { reflect: boolean }): PropertyDecorator;',
      "@element('oe-spike-unsupported-condition')",
      'export class UnsupportedCondition extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      '  render() { return <div>{this.count === 1 ? <p>one</p> : <p>other</p>}</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsupported-condition.tsx'),
      Error,
      'finite numeric literal',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9013');
  });

  await t.step('list Regions reject multiple item value slots', () => {
    const source = [
      "import { OpenElement } from '@openelement/element';",
      'declare function element(tag: string): ClassDecorator;',
      'declare function property(options: { reflect: boolean }): PropertyDecorator;',
      "@element('oe-spike-duplicate-item-value')",
      'export class DuplicateItemValue extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', text: 'alpha' }];",
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id}>{item.text}{item.text}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/duplicate-item-value.tsx'),
      Error,
      'exactly one',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9013');
  });
});

Deno.test('compiled-element alpha.1 - canonical program records and decorator lowering', async () => {
  const { compiledElementPlugin } = await loadPluginModule();
  const transform = transformOf(compiledElementPlugin());
  const source = [
    "import { OpenElement } from '@openelement/element';",
    'declare function element(tag: string): ClassDecorator;',
    'declare function property(options: { type?: unknown; attribute?: string | false; reflect?: boolean }): PropertyDecorator;',
    "@element('oe-alpha-one')",
    'export class AlphaOne extends OpenElement {',
    '  @property({ type: Number, reflect: true })',
    '  count = 0;',
    "  @property({ type: Boolean, attribute: 'enabled' })",
    '  enabled = false;',
    '  render() {',
    '    return <button disabled={this.enabled} onClick={() => this.count++}>Count: {this.count}</button>;',
    '  }',
    '}',
  ].join('\n');
  const id = '/project/app/islands/alpha-one.tsx';
  const emitted = transform.call(failingContext(), source, id);
  assert(typeof emitted === 'string');

  const marker = 'const __partProgram = ';
  const start = emitted.indexOf(marker);
  assert(start >= 0, 'generated code must embed the Part Program literal');
  const end = emitted.indexOf(';', start);
  const program = JSON.parse(emitted.slice(start + marker.length, end));

  assertEquals(program.version, 1);
  assertEquals(program.root, { id: 'root', kind: 'light', nodes: ['e0'] });
  assertEquals(program.parts.map((part: { k: string }) => part.k), ['bool', 'event', 'text']);
  assertEquals(program.parts[0].location, {
    id: 'p0',
    kind: 'sink',
    node: 'e0',
    path: [0],
  });
  assertEquals(program.dependencies, [
    { signal: 'enabled', owner: { kind: 'part', index: 0 }, location: 'p0' },
    { signal: 'count', owner: { kind: 'part', index: 2 }, location: 'p2' },
  ]);
  assertEquals(program.metadata.properties, [
    {
      name: 'count',
      attribute: 'count',
      type: 'number',
      converter: 'number',
      reflect: true,
      default: 0,
    },
    {
      name: 'enabled',
      attribute: 'enabled',
      type: 'boolean',
      converter: 'boolean',
      reflect: false,
      default: false,
    },
  ]);
  assertEquals(program.metadata.observedAttributes, ['count', 'enabled']);
  assert(
    program.sourceMap.records.some((record: { id: string; source: { file: string } }) =>
      record.id === 'p0' && record.source.file === id
    ),
  );
  assertStringIncludes(emitted, 'static observedAttributes = __observedAttributes;');
  assertStringIncludes(emitted, 'static props = __compiledProps;');
  assertEquals(emitted.includes('@element'), false);
  assertEquals(emitted.includes('@property'), false);
  assertEquals(emitted.includes('accessor '), false);
});

Deno.test('compiled-element alpha.1 - program validation fails closed on unsafe identity', async () => {
  const [{ compileElementSpike }, { validatePartProgram }] = await Promise.all([
    import('../src/internal/compiler/compile.ts'),
    import('../src/internal/compiler/program.ts'),
  ]);
  const source = await readFixture('counter.tsx');
  const program = compileElementSpike(source, '/project/app/islands/counter.tsx').program;

  const shiftedLocation = structuredClone(program) as {
    parts: Array<{ location: { path: number[] } }>;
  };
  shiftedLocation.parts[1].location.path = [0];
  assertThrows(() => validatePartProgram(shiftedLocation), Error, 'location path');

  const shiftedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  shiftedElementLocation.locations[0].path = [0, 99];
  assertThrows(
    () => validatePartProgram(shiftedElementLocation),
    Error,
    'locations[0] element',
  );

  const renamedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  renamedElementLocation.locations[0].tag = 'span';
  assertThrows(
    () => validatePartProgram(renamedElementLocation),
    Error,
    'locations[0] element',
  );

  const mismatchedItemField = structuredClone(program) as {
    parts: Array<{
      item?: Array<{ children?: Array<{ field?: string }> }>;
    }>;
  };
  mismatchedItemField.parts[4].item![0].children![0].field = 'id';
  assertThrows(
    () => validatePartProgram(mismatchedItemField),
    Error,
    'must use item field',
  );

  const mismatchedRegionSource = structuredClone(program) as {
    regions: Array<{ source: string }>;
  };
  mismatchedRegionSource.regions[0].source = 'p0';
  assertThrows(
    () => validatePartProgram(mismatchedRegionSource),
    Error,
    'regions[0]',
  );

  const unknownPart = structuredClone(program) as { parts: Array<{ k: string }> };
  unknownPart.parts[0].k = 'future';
  assertThrows(() => validatePartProgram(unknownPart), Error, 'unknown part kind');
});
