import { css, html, LitElement } from '@kissjs/core';

export const tagName = 'df-about';

export default class DfAbout extends LitElement {
  static override styles = css`
    :host { display: block; max-width: 560px; margin: 0 auto; padding: 3rem 2rem; }
    .back { display: inline-block; margin-bottom: 1.5rem; text-decoration: none; color: #555; font-size: 0.875rem; }
    .back:hover { color: #000; }
    h1 { font-size: 1.5rem; margin: 0 0 0.75rem; }
    p { font-size: 0.9375rem; line-height: 1.7; color: #444; margin: 0 0 0.75rem; }
    .step { padding: 0.75rem 1rem; border: 1px solid #eee; border-radius: 6px; margin-bottom: 0.75rem; }
    .step h3 { font-size: 0.875rem; margin: 0 0 0.25rem; }
    .step p { font-size: 0.8125rem; margin: 0; color: #666; }
  `;

  override render() {
    return html`
      <a class="back" href="/demo/">← Home</a>
      <h1>How This Was Built</h1>
      <p>This entire site was generated by the KISS 3-phase build pipeline:</p>
      <div class="step">
        <h3>Phase 1: <code>npx vite build</code></h3>
        <p>Vite bundles the SSR entry point. Route scanner finds 2 pages + 1 island. Writes <code>.kiss/build-metadata.json</code>.</p>
      </div>
      <div class="step">
        <h3>Phase 2: <code>build:client</code></h3>
        <p>Builds the island client chunks — the counter island becomes a ~1.2 KB lazy-loaded JS file.</p>
      </div>
      <div class="step">
        <h3>Phase 3: <code>build:ssg</code></h3>
        <p>Renders every page to static HTML with Declarative Shadow DOM. Injects client script + PWA manifest. Generates <code>404.html</code>.</p>
      </div>
      <p style="color:#888;font-size:0.8125rem;margin-top:1rem">Result: pure static files. No server. No hydration. Zero runtime JS for static content.</p>
    `;
  }
}
