/**
 * blog-data.ts - Generated blog data module writer
 *
 * Collection scanning and markdown parsing are owned by the generic content
 * collection pipeline. This module only serializes its normalized BlogPost
 * records for application routes.
 */

import type { BlogPost } from './types.ts';

/**
 * Generate TypeScript module source code for blog data.
 * The output is a self-contained .ts file that exports posts and
 * getPostBySlug().
 *
 * SOP-001: Virtual Modules Removal — replaces @openelement/generated/blog-data.
 *
 * @param posts - Array of parsed blog posts
 * @returns TypeScript module source string
 */
export function writeBlogDataModule(posts: BlogPost[]): string {
  return [
    '// Auto-generated by @openelement/adapter-vite blog-data - do not edit',
    'export interface GeneratedBlogPost {',
    '  slug: string;',
    '  frontmatter: {',
    '    title: string;',
    '    date: string;',
    '    draft?: boolean;',
    '    tags?: string[];',
    '    excerpt?: string;',
    '    type?: string;',
    '  };',
    '  content: string;',
    '  html: string;',
    '}',
    '',
    `export const posts: GeneratedBlogPost[] = ${JSON.stringify(posts, null, 2)};`,
    '',
    'export function getPostBySlug(slug: string): GeneratedBlogPost | undefined {',
    '  return posts.find((p) => p.slug === slug);',
    '}',
  ].join('\n') + '\n';
}
