/**
 * writer.ts - Navigation writer modules
 *
 * Pure serialization helpers that turn scanned NavData into TypeScript
 * source strings. Extracted from index.ts so the nav plugin can be
 * tested with an in-memory file-system adapter.
 */

import type { NavData } from './scanner.ts';

/**
 * Generate TypeScript module source code for navigation data.
 * The output is a self-contained .ts file that exports headerNav
 * and navSections directly.
 *
 * @param data - Aggregated navigation data from scanNavData()
 * @returns TypeScript module source string
 */
export function writeNavModule(data: NavData): string {
  return [
    '// Auto-generated by @openelement/adapter-vite nav-writer — do not edit',
    `export const headerNav = ${JSON.stringify(data.headerNav, null, 2)};`,
    `export const navSections = ${JSON.stringify(data.navSections, null, 2)};`,
  ].join('\n') + '\n';
}
