import matter from 'gray-matter';
import { marked } from 'marked';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { sanitizeContentHtml } from '../sanitize.ts';
import { collectionFieldTypeScript, validateCollectionFrontmatter } from './schema.ts';
import type { CollectionEntry, CollectionOptions } from './types.ts';

export async function loadCollectionData(
  name: string,
  options: CollectionOptions,
): Promise<CollectionEntry[]> {
  if (!existsSync(options.contentDir)) return [];
  const entries: CollectionEntry[] = [];
  for (const fileName of readdirSync(options.contentDir).sort()) {
    if (!fileName.endsWith('.md') && !fileName.endsWith('.mdx')) continue;
    const filePath = join(options.contentDir, fileName);
    const source = readFileSync(filePath, 'utf-8');
    const parsed = matter(source);
    const initialSlug = fileName.replace(/\.mdx?$/, '');
    const result = validateCollectionFrontmatter(
      options.schema,
      parsed.data as Record<string, unknown>,
      { collection: name, fileName, filePath, slug: initialSlug },
    );
    const rawHtml = options.markdown
      ? await options.markdown(parsed.content)
      : await marked(parsed.content, { async: true });
    entries.push({
      slug: result.slug ?? initialSlug,
      ...(typeof result.frontmatter.locale === 'string'
        ? { locale: result.frontmatter.locale }
        : {}),
      frontmatter: result.frontmatter,
      content: parsed.content,
      html: sanitizeContentHtml(rawHtml),
    });
  }
  return entries;
}

export function writeCollectionDataModule(
  name: string,
  entries: CollectionEntry[],
  options: CollectionOptions,
): string {
  const fields = options.schema
    ? Object.entries(options.schema.fields).map(([fieldName, raw]) => {
      const field = collectionFieldTypeScript(raw);
      return `    ${JSON.stringify(fieldName)}${field.optional ? '?' : ''}: ${field.type};`;
    })
    : ['    [key: string]: unknown;'];
  return [
    `// Auto-generated by @openelement/adapter-vite collection:${name} - do not edit`,
    'export interface GeneratedCollectionEntry {',
    '  slug: string;',
    ...(options.schema?.fields.locale ? ['  locale: string;'] : ['  locale?: string;']),
    '  frontmatter: {',
    ...fields,
    '  };',
    '  content: string;',
    '  html: string;',
    '}',
    '',
    `export const pages: GeneratedCollectionEntry[] = ${JSON.stringify(entries, null, 2)};`,
    '',
    'export function getPage(slug: string, locale?: string): GeneratedCollectionEntry | undefined {',
    '  return pages.find((page) => page.slug === slug && (locale === undefined || page.locale === locale));',
    '}',
    '',
  ].join('\n');
}
