/**
 * @openelement/adapter-vite - Route Type Generator
 *
 * Generates `.openElement/routes.d.ts` with type-safe route parameter definitions
 * for the `virtual:open-routes` module. Only routes that have dynamic [param]
 * segments are included in the output.
 *
 * v0.25.0: Initial implementation for build-time route type code generation.
 */

import type { RouteEntry } from '@openelement/protocol/framework';
import { parseRouteFilePath } from './route-scanner.ts';
import { quoteGeneratedJavaScriptStringLiteral } from './codegen-literals.ts';

/**
 * Generate TypeScript type literal for route params.
 * Converts param names to a Record<string, string> type.
 *
 * Example: ['slug'] → `{ slug: string }`
 * Example: ['package', 'component'] → `{ package: string; component: string }`
 */
function generateParamsType(params: string[]): string {
  if (params.length === 0) {
    return 'Record<string, never>';
  }
  const fields = params.map((p) => `${p}: string`);
  return `{ ${fields.join('; ')} }`;
}

/**
 * Generate the `.openElement/routes.d.ts` declaration file content.
 *
 * Only routes that have dynamic parameters (non-empty `params` array)
 * are included in the generated output. Static routes with no params
 * are excluded since they don't need type-safe parameter access.
 *
 * Example output:
 * ```typescript
 * declare module 'virtual:open-routes' {
 *   interface RouteParams {
 *     '/blog/[slug]': { slug: string };
 *     '/registry/[package]/[component]': { package: string; component: string };
 *   }
 * }
 * ```
 *
 * @param routes - Array of route entries from the route scanner
 * @returns TypeScript declaration file content as a string
 */
export function generateRouteTypes(routes: RouteEntry[]): string {
  // Filter for page routes that have dynamic params
  const paramRoutes = routes.filter(
    (r) => r.type === 'page' && r.params && r.params.length > 0,
  );

  if (paramRoutes.length === 0) {
    // No routes with params - generate a placeholder interface
    return [
      '/**',
      ' * Auto-generated by @openelement/adapter-vite (v0.25.0)',
      ' * DO NOT EDIT MANUALLY',
      ' */',
      '',
      "declare module 'virtual:open-routes' {",
      '  // eslint-disable-next-line @typescript-eslint/no-empty-interface',
      '  export interface RouteParams {',
      '  }',
      '}',
      '',
    ].join('\n');
  }

  // Generate entries for each route with params
  const paramEntries = paramRoutes.map((r) => {
    const bracketPath = parseRouteFilePath(r.filePath, { paramSyntax: 'bracket' });
    const path = quoteGeneratedJavaScriptStringLiteral(bracketPath);
    const type = generateParamsType(r.params!);
    return `    ${path}: ${type};`;
  });

  return [
    '/**',
    ' * Auto-generated by @openelement/adapter-vite (v0.25.0)',
    ' * DO NOT EDIT MANUALLY',
    ' */',
    '',
    "declare module 'virtual:open-routes' {",
    '  export interface RouteParams {',
    ...paramEntries,
    '  }',
    '}',
    '',
  ].join('\n');
}
