/** @jsxImportSource @openelement/element */
import { defineElement } from '@openelement/app';
import { StyleSheet } from '@openelement/element';

export const tagName = 'app-shell';

interface HeaderNavLink {
  href: string;
  label: string;
}

// Fallback when vite.config.ts content.nav.headerNav is not configured.
const defaultNav: HeaderNavLink[] = [
  { href: '/freshness', label: 'Freshness' },
  { href: '/api/health', label: 'API health' },
];

const styles = new StyleSheet();
styles.replaceSync(`
  :host { display: block; min-height: 100vh; }
  header {
    position: sticky; top: 0; z-index: 10;
    background: rgba(255, 255, 255, 0.78);
    backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid var(--gray-3);
  }
  .bar { max-width: 920px; margin: 0 auto; padding: 0.85rem 1.25rem; display: flex; justify-content: space-between; align-items: center; }
  .brand { display: flex; align-items: center; gap: 0.55rem; font-weight: 800; font-size: 1.05rem; letter-spacing: -0.01em; color: var(--gray-9); }
  .brand::before { content: ''; width: 12px; height: 12px; border-radius: 4px; background: linear-gradient(135deg, var(--brand), var(--brand-2)); }
  nav { display: flex; gap: 0.25rem; }
  nav a { padding: 0.4rem 0.8rem; border-radius: 999px; color: var(--gray-7); font-size: 0.925rem; }
  nav a:hover { background: #8262db14; color: var(--brand); text-decoration: none; }
  main { max-width: 920px; margin: 0 auto; padding: 2.5rem 1.25rem; }
  footer { border-top: 1px solid var(--gray-3); color: var(--gray-7); font-size: 0.875rem; }
  .foot { max-width: 920px; margin: 0 auto; padding: 1.25rem; display: flex; justify-content: space-between; gap: 1rem; }
  a { color: var(--brand); text-decoration: none; font-weight: 600; }
`);

export default defineElement(tagName, {
  styles,
  render(props: { siteName?: string; headerNav?: HeaderNavLink[] }) {
    const nav = props.headerNav?.length ? props.headerNav : defaultNav;
    return (
      <>
        <header data-open-layout='app-shell'>
          <div class='bar'>
            <a class='brand' href='/'>{props.siteName ?? 'openElement'}</a>
            <nav>
              {nav.map((link) => <a key={link.href} href={link.href}>{link.label}</a>)}
            </nav>
          </div>
        </header>
        <main>
          <slot></slot>
        </main>
        <footer>
          <div class='foot'>
            <span>Generated by @openelement/create.</span>
            <a href='https://github.com/open-element/openelement'>GitHub</a>
          </div>
        </footer>
      </>
    );
  },
});
