/** @jsxImportSource @openelement/element */
import { defineElement } from '@openelement/app';
import { StyleSheet } from '@openelement/element';

export const tagName = 'app-shell';

interface HeaderNavLink {
  href: string;
  label: string;
}

// Fallback when vite.config.ts content.nav.headerNav is not configured.
const defaultNav: HeaderNavLink[] = [
  { href: '/freshness', label: 'Freshness' },
  { href: '/api/health', label: 'API health' },
];

const styles = new StyleSheet();
styles.replaceSync(`
  :host { display: block; min-height: 100vh; background: var(--gray-1); }
  header, main, footer { max-width: 860px; margin: 0 auto; padding: 1rem; }
  header { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid var(--gray-3); }
  nav { display: flex; gap: 1.25rem; }
  footer { color: var(--gray-7); font-size: 0.875rem; border-top: 1px solid var(--gray-3); }
  a { color: var(--brand); text-decoration: none; font-weight: 600; }
  a:hover { text-decoration: underline; }
`);

export default defineElement(tagName, {
  styles,
  render(props: { siteName?: string; headerNav?: HeaderNavLink[] }) {
    const nav = props.headerNav?.length ? props.headerNav : defaultNav;
    return (
      <>
        <header data-open-layout='app-shell'>
          <a href='/'>{props.siteName ?? 'openElement'}</a>
          <nav>
            {nav.map((link) => <a key={link.href} href={link.href}>{link.label}</a>)}
          </nav>
        </header>
        <main>
          <slot></slot>
        </main>
        <footer>Generated by @openelement/create.</footer>
      </>
    );
  },
});
