/** @jsxImportSource @openelement/element */
import { defineElement } from '@openelement/app';
import { StyleSheet } from '@openelement/element';

export const tagName = 'app-shell';

interface HeaderNavLink {
  href: string;
  label: string;
}

// Fallback when vite.config.ts content.nav.headerNav is not configured.
const defaultNav: HeaderNavLink[] = [
  { href: '/freshness', label: 'Freshness' },
  { href: '/api/health', label: 'API health' },
];

const styles = new StyleSheet();
styles.replaceSync(`
  :host { display: block; min-height: 100vh; }
  header { border-bottom: 1px solid var(--line); }
  .bar { max-width: 740px; margin: 0 auto; padding: 1.15rem 1.25rem; display: flex; justify-content: space-between; align-items: baseline; }
  .brand { font-family: var(--font-serif); font-weight: 700; font-size: 1.2rem; letter-spacing: -0.01em; color: var(--ink); }
  .brand:hover { text-decoration: none; color: var(--brand); }
  nav { display: flex; gap: 1.5rem; }
  nav a { color: var(--ink-2); font-size: 0.95rem; font-weight: 500; }
  nav a:hover { color: var(--brand); text-decoration: none; }
  main { max-width: 740px; margin: 0 auto; padding: 3rem 1.25rem 4rem; }
  footer { border-top: 1px solid var(--line); color: var(--ink-2); font-size: 0.85rem; }
  .foot { max-width: 740px; margin: 0 auto; padding: 1.25rem; display: flex; justify-content: space-between; gap: 1rem; }
  a { color: var(--brand); text-decoration: none; }
  a:hover { text-decoration: underline; }
`);

export default defineElement(tagName, {
  styles,
  render(props: { siteName?: string; headerNav?: HeaderNavLink[] }) {
    const nav = props.headerNav?.length ? props.headerNav : defaultNav;
    return (
      <>
        <header data-open-layout='app-shell'>
          <div class='bar'>
            <a class='brand' href='/'>{props.siteName ?? 'openElement'}</a>
            <nav>
              {nav.map((link) => <a key={link.href} href={link.href}>{link.label}</a>)}
            </nav>
          </div>
        </header>
        <main>
          <slot></slot>
        </main>
        <footer>
          <div class='foot'>
            <span>Generated by @openelement/create.</span>
            <a href='https://github.com/open-element/openelement'>GitHub</a>
          </div>
        </footer>
      </>
    );
  },
});
