// deno-fmt-ignore-file
// deno-lint-ignore-file
// This file is generated by Fresh.

import * as $_routes_index from "./routes/index.tsx";
import * as $_islands_open_elements from "./islands/OpenElements.tsx";
import * as $_islands_preact_counter from "./islands/PreactCounter.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $_routes_index,
  },
  islands: {
    "./islands/OpenElements.tsx": $_islands_open_elements,
    "./islands/PreactCounter.tsx": $_islands_preact_counter,
  },
  baseUrl: import.meta.url,
};

export default manifest;
