// GENERATED FILE — do not edit by hand.
// Regenerate with: deno task export-files:generate
// Source of truth: the "exports" field of each packages/*/deno.json.
export const OPENELEMENT_EXPORT_FILES: Record<string, Record<string, string>> = {
  'adapter-vite': {
    '.': 'src/index.ts',
    'app-vite': 'src/app-vite.ts',
    'build-context': 'src/build-context.ts',
    'cli/build': 'src/cli/build.ts',
    'cli/build-client': 'src/cli/build-client.ts',
    'cli/build-ssg': 'src/cli/build-ssg.ts',
    'generated-data-resolver': 'src/generated-data-resolver.ts',
    'head-injection': 'src/head-injection.ts',
    'i18n-plugin': 'src/i18n-plugin.ts',
    'nitro-mount': 'src/nitro-mount.ts',
    'plugin': 'src/plugin.ts',
    'plugin-mdx': 'src/plugin-mdx.ts',
    'route-manifest': 'src/route-manifest.ts',
    'sitemap': 'src/sitemap.ts',
  },
  'app': {
    '.': 'src/index.ts',
    'hono': 'src/hono.ts',
    'i18n': 'src/i18n.ts',
    'model': 'src/model.ts',
    'preact': 'src/preact.ts',
    'spa': 'src/spa.ts',
  },
  'create': {
    '.': 'src/cli.ts',
  },
  'element': {
    '.': 'src/index.ts',
    'build-utils': 'src/build-utils.ts',
    'jsx-dev-runtime': 'src/jsx-dev-runtime.ts',
    'jsx-runtime': 'src/jsx-runtime.ts',
    'open-element-hydration': 'src/open-element-hydration.ts',
    'open-element-render': 'src/open-element-render.ts',
  },
  'ui': {
    '.': 'src/index.ts',
    'open-badge': 'src/open-badge.tsx',
    'open-button': 'src/open-button.tsx',
    'open-callout': 'src/open-callout.tsx',
    'open-card': 'src/open-card.tsx',
    'open-code-block': 'src/open-code-block.tsx',
    'open-dialog': 'src/open-dialog.tsx',
    'open-dropdown': 'src/open-dropdown.tsx',
    'open-input': 'src/open-input.tsx',
    'open-props-tokens': 'src/open-props-tokens.ts',
    'open-props-tokens.js': 'src/open-props-tokens.ts',
    'open-tabs': 'src/open-tabs.tsx',
    'open-theme-toggle': 'src/open-theme-toggle.tsx',
  },
};
