// deno-api-free:ignore
/**
 * Internal Node-only Vite plugin for i18n.
 *
 * Build-time Vite plugin, allowed to use node:*.
 *
 * This module uses node:process, node:path, node:fs and MUST NOT be imported
 * from the main @openelement/app entry to avoid pulling Node built-ins into
 * client island bundles.
 *
 * Standalone usage requires explicit ctx parameter:
 * ```ts
 * openI18n({ locales: ['en', 'zh'], defaultLocale: 'en', ctx });  // ctx must be explicitly passed
 * ```
 */

import type { Plugin } from 'vite';
import type { OpenElementBuildContextLike } from './internal/protocol/framework.ts';
import { createLogger } from '@openelement/element';
import { formatError } from '@openelement/element';
import process from 'node:process';
import { join } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';
import { loadI18nData } from '@openelement/app/i18n';
import type { OpenElementI18nOptions } from '@openelement/app/i18n';

const log = createLogger('i18n');

// ─── Data utilities (node-only) ───────────────────────────────────

/**
 * Generate TypeScript module source code for i18n configuration.
 * The output is a self-contained .ts file that exports locales,
 * defaultLocale, and helper functions.
 *
 * SOP-001: Virtual Modules Removal — replaces @openelement/generated/i18n.
 *
 * @param locales - Array of locale code strings (e.g. ['en', 'zh'])
 * @param defaultLocale - Default locale code (e.g. 'en')
 * @returns TypeScript module source string
 */
export function writeI18nDataModule(locales: string[], defaultLocale: string): string {
  return [
    '// Auto-generated by @openelement/adapter-vite/i18n — do not edit',
    `export const locales = ${JSON.stringify(locales)};`,
    `export const defaultLocale = "${defaultLocale}";`,
    '',
    'export function getDefaultLocale(): string { return defaultLocale; }',
    'export function getI18nOptions() { return { locales, defaultLocale }; }',
  ].join('\n') + '\n';
}

// ─── Vite plugin ─────────────────────────────────────────────────

/**
 * openElement i18n Vite plugin.
 * Configures locale options for route-level i18n helpers.
 */
export function openI18n(
  options: OpenElementI18nOptions & { ctx?: OpenElementBuildContextLike },
): Plugin {
  // ctx must be explicitly provided (via openElement() umbrella or direct param)
  const ctx = options.ctx;

  return {
    name: 'open:i18n',

    buildStart() {
      // ADR 0018: Use loadI18nData() pure function - zero module state
      const i18nData = loadI18nData(options);

      // Write i18n options to ctx (shared build context)
      // The @openelement/generated/i18n plugin reads ctx.plugins.i18nOptions in its load() hook
      if (ctx) {
        ctx.registerPlugin('i18nOptions', {
          locales: i18nData.locales,
          defaultLocale: i18nData.defaultLocale,
        });
      }

      // SOP-001: Write generated i18n data module to disk
      try {
        const dataDir = join(process.cwd(), 'app', 'data');
        mkdirSync(dataDir, { recursive: true });
        const i18nModule = writeI18nDataModule(i18nData.locales, i18nData.defaultLocale);
        writeFileSync(join(dataDir, '_generated-i18n-data.ts'), i18nModule, 'utf-8');
        log.info(`I18n: wrote _generated-i18n-data.ts (${i18nData.locales.join(', ')})`);
      } catch (err) {
        log.warn(
          `Failed to write _generated-i18n-data.ts: ${formatError(err)}`,
        );
      }

      log.info(`${options.locales.join(', ')} (default: ${options.defaultLocale})`);
    },
  };
}

// Use @openelement/app/i18n for runtime helpers: i18nStaticPaths, loadI18nData, switchLocale, normalizeLocalePath

export default openI18n;
