/**
 * Route manifest generator for SPA mode client routing.
 *
 * Scans the project's routes directory and generates a TypeScript manifest
 * that maps URL paths to lazy import() calls. The generated file is bundled
 * by Vite for client-side route lazy loading.
 *
 * ## Usage (SPA mode)
 *
 * ```ts
 * // In your client entry:
 * import { routeManifest } from '../.openelement/route-manifest';
 * import { createRouter } from '@openelement/router/client-router';
 *
 * const router = createRouter({
 *   mode: 'history',
 *   routes: Object.entries(routeManifest).map(([path, component]) => ({
 *     path,
 *     component,
 *   })),
 * });
 * ```
 *
 * ## File System Convention
 *
 * - `routes/index.tsx`          → `/`
 * - `routes/products.tsx`       → `/products`
 * - `routes/products/[id].tsx`  → `/products/:id`
 * - `routes/products/index.tsx` → `/products`
 * - `routes/products/[...slug].tsx` → `/products/*` (catch-all)
 *
 * @module route-manifest
 */

import { scanRoutes } from '@openelement/ssg';
import { dirname, join, posix, sep } from 'node:path';

/**
 * Parameters for route manifest generation.
 */
export interface GenerateRouteManifestOptions {
  /** Project routes directory (default: 'app/routes') */
  routesDir?: string;
  /** Output directory for the generated manifest file */
  outDir: string;
}

/**
 * Generate a TypeScript module string for the route manifest.
 *
 * Scans the routes directory, filters to page routes, and produces
 * a `routeManifest` constant mapped to lazy import() calls.
 *
 * @param routesDir - Absolute path to the routes directory
 * @param manifestPath - Absolute path where the manifest file will be written
 * @returns Generated TypeScript source code
 */
export async function generateRouteManifestContent(
  routesDir: string,
  manifestPath: string,
): Promise<string> {
  const routes = await scanRoutes(routesDir);
  const pageRoutes = routes.filter((r) => r.type === 'page' && !r.special);

  const manifestDir = dirname(manifestPath);

  const entries = pageRoutes.map((r) => {
    const absFilePath = join(routesDir, r.filePath);
    const importPath = relativeToOutput(absFilePath, manifestDir);
    return `  '${r.path}': () => import('${importPath}')`;
  });

  if (entries.length === 0) {
    return `// Auto-generated by @openelement/adapter-vite — do not edit.
// No page routes found in "${routesDir}".
export const routeManifest = {} as const;
`;
  }

  return `// Auto-generated by @openelement/adapter-vite — do not edit.
export const routeManifest = {
${entries.join(',\n')}
} as const;
`;
}

/**
 * Compute a relative import path from the manifest output directory to a
 * source file, ensuring posix separators and a leading `./` prefix.
 *
 * @param absSourcePath - Absolute path to the source file (route module)
 * @param fromDir - Absolute directory from which the import originates
 * @returns Relative import path string
 */
function relativeToOutput(absSourcePath: string, fromDir: string): string {
  // Compute the relative path
  const parts = absSourcePath.replaceAll(sep, posix.sep).split(posix.sep);
  const fromParts = fromDir.replaceAll(sep, posix.sep).split(posix.sep);

  // Strip common prefix
  let i = 0;
  while (i < parts.length && i < fromParts.length && parts[i] === fromParts[i]) {
    i++;
  }

  const upCount = fromParts.length - i;
  const remaining = parts.slice(i);

  let result = '';
  if (upCount > 0) {
    result = '../'.repeat(upCount);
  } else {
    result = './';
  }
  result += remaining.join(posix.sep);

  // Ensure it always starts with '.' (relative import)
  if (!result.startsWith('.')) {
    result = './' + result;
  }

  return result;
}

/**
 * Ensure the output directory exists, then write the route manifest file.
 *
 * @param options - Generation options
 * @returns The number of page routes written
 */
export async function writeRouteManifest(
  options: GenerateRouteManifestOptions,
): Promise<number> {
  const { routesDir = 'app/routes', outDir } = options;
  const manifestPath = join(outDir, 'route-manifest.ts');

  // ponytail: Deno.mkdir is built-in, no need for ensureDir dep
  try {
    await Deno.mkdir(outDir, { recursive: true });
  } catch {
    // Directory already exists
  }
  const content = await generateRouteManifestContent(routesDir, manifestPath);
  await Deno.writeTextFile(manifestPath, content);

  // Count page routes from generated content
  const matches = content.match(/=> import\(/g);
  return matches ? matches.length : 0;
}
