/**
 * Route manifest generator for SPA mode client routing.
 *
 * Scans the project's routes directory and generates a TypeScript manifest
 * that maps URL paths to lazy import() calls. The generated file is bundled
 * by Vite for client-side route lazy loading.
 *
 * ## Usage (SPA mode)
 *
 * ```ts
 * // Generated to `${outDir}/route-manifest.ts`; import from that generated
 * // module or alias it from your client entry.
 * import { routeManifest } from './route-manifest.ts';
 * import { createRouter } from '@openelement/router/client-router';
 *
 * const router = createRouter({
 *   mode: 'history',
 *   routes: Object.entries(routeManifest).map(([path, component]) => ({
 *     path,
 *     component,
 *   })),
 * });
 * ```
 *
 * ## File System Convention
 *
 * - `routes/index.tsx`          → `/`
 * - `routes/products.tsx`       → `/products`
 * - `routes/products/[id].tsx`  → `/products/:id`
 * - `routes/products/index.tsx` → `/products`
 * - `routes/products/[...slug].tsx` → `/products/*` (catch-all)
 *
 * @module route-manifest
 */

import { scanRoutes } from '@openelement/ssg';
import { dirname, join, posix, sep, win32 } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';

/**
 * Parameters for route manifest generation.
 */
export interface GenerateRouteManifestOptions {
  /** Project routes directory (default: 'app/routes') */
  routesDir?: string;
  /** Output directory for the generated manifest file */
  outDir: string;
}

interface RouteManifestGeneration {
  content: string;
  count: number;
}

/**
 * Generate a TypeScript module string for the route manifest.
 *
 * Scans the routes directory, filters to page routes, and produces
 * a `routeManifest` constant mapped to lazy import() calls.
 *
 * @param routesDir - Absolute path to the routes directory
 * @param manifestPath - Absolute path where the manifest file will be written
 * @returns Generated TypeScript source code
 */
export async function generateRouteManifestContent(
  routesDir: string,
  manifestPath: string,
): Promise<string> {
  return (await generateRouteManifest(routesDir, manifestPath)).content;
}

async function generateRouteManifest(
  routesDir: string,
  manifestPath: string,
): Promise<RouteManifestGeneration> {
  const routes = await scanRoutes(routesDir);
  const pageRoutes = routes.filter((r) => r.type === 'page' && !r.special);

  const manifestDir = dirname(manifestPath);

  const entries = pageRoutes.map((r) => {
    const absFilePath = join(routesDir, r.filePath);
    const importPath = relativeToOutput(absFilePath, manifestDir);
    return `  '${r.path}': () => import('${importPath}')`;
  });

  if (entries.length === 0) {
    return {
      count: 0,
      content: `// Auto-generated by @openelement/adapter-vite — do not edit.
// No page routes found in "${routesDir}".
export const routeManifest = {} as const;
`,
    };
  }

  return {
    count: entries.length,
    content: `// Auto-generated by @openelement/adapter-vite — do not edit.
export const routeManifest = {
${entries.join(',\n')}
} as const;
`,
  };
}

/**
 * Compute a relative import path from the manifest output directory to a
 * source file, ensuring posix separators and a leading `./` prefix.
 *
 * @param absSourcePath - Absolute path to the source file (route module)
 * @param fromDir - Absolute directory from which the import originates
 * @returns Relative import path string
 */
function relativeToOutput(absSourcePath: string, fromDir: string): string {
  const sourceDrive = win32.parse(absSourcePath).root.toLowerCase();
  const fromDrive = win32.parse(fromDir).root.toLowerCase();
  if (sourceDrive && fromDrive && sourceDrive !== fromDrive) {
    throw new Error(
      `Cannot generate relative route import across Windows drives: ${fromDir} -> ${absSourcePath}`,
    );
  }

  // Compute the relative path
  const parts = absSourcePath.replaceAll(sep, posix.sep).split(posix.sep);
  const fromParts = fromDir.replaceAll(sep, posix.sep).split(posix.sep);

  // Strip common prefix
  let i = 0;
  while (i < parts.length && i < fromParts.length && parts[i] === fromParts[i]) {
    i++;
  }

  const upCount = fromParts.length - i;
  const remaining = parts.slice(i);

  let result = '';
  if (upCount > 0) {
    result = '../'.repeat(upCount);
  } else {
    result = './';
  }
  result += remaining.join(posix.sep);

  // Ensure it always starts with '.' (relative import)
  if (!result.startsWith('.')) {
    result = './' + result;
  }

  return result;
}

/**
 * Ensure the output directory exists, then write the route manifest file.
 *
 * @param options - Generation options
 * @returns The number of page routes written
 */
export async function writeRouteManifest(
  options: GenerateRouteManifestOptions,
): Promise<number> {
  const { routesDir = 'app/routes', outDir } = options;
  const manifestPath = join(outDir, 'route-manifest.ts');

  await mkdir(outDir, { recursive: true });
  const { content, count } = await generateRouteManifest(routesDir, manifestPath);
  await writeFile(manifestPath, content, 'utf-8');
  return count;
}
