/** Generate the importable UI token module from its CSS source of truth. */

const ROOT = new URL('../', import.meta.url);
const CSS_SOURCE = new URL('packages/ui/src/open-props-tokens.css', ROOT);
const TARGET = new URL('packages/ui/src/open-props-tokens.ts', ROOT);
const check = Deno.args.includes('--check');
const bootstrap = Deno.args.includes('--bootstrap');

function extractLegacyCss(source: string): string {
  const prefix = 'const tokenCss = `';
  const start = source.indexOf(prefix);
  const end = source.indexOf('\n`;\n\nsheet.replaceSync', start);
  if (start < 0 || end < 0) throw new Error('Could not extract legacy tokenCss template');
  return source.slice(start + prefix.length, end)
    .replaceAll('\\`', '`')
    .replaceAll('\\${', '${');
}

if (bootstrap) {
  try {
    await Deno.stat(CSS_SOURCE);
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
    const legacy = await Deno.readTextFile(TARGET);
    await Deno.writeTextFile(CSS_SOURCE, extractLegacyCss(legacy));
  }
}

const css = await Deno.readTextFile(CSS_SOURCE);
const cssTemplate = css
  .replaceAll('\\', '\\\\')
  .replaceAll('`', '\\`')
  .replaceAll('${', '\\${');
const generated = `/**
 * @generated from open-props-tokens.css by tools/generate-ui-token-module.ts.
 * Do not edit this file directly.
 */

import { StyleSheet, type StyleSheetLike } from '@openelement/element';

function toRootCss(hostCss: string): string {
  return hostCss
    .replace(/:host\\(\\[data-theme='dark'\\]\\)/g, ":root[data-theme='dark']")
    .replace(/:host/g, ':root');
}

const OPEN_PROPS_TOKEN_CSS = \`${cssTemplate}\`;

const sheet: StyleSheetLike = new StyleSheet();
sheet.replaceSync(OPEN_PROPS_TOKEN_CSS);
export const openPropsTokenSheet: StyleSheetLike = sheet;

export const openPropsRootSheet: StyleSheetLike = new StyleSheet();
openPropsRootSheet.replaceSync(toRootCss(OPEN_PROPS_TOKEN_CSS));
`;

if (check) {
  const current = await Deno.readTextFile(TARGET);
  if (current !== generated) {
    console.error('UI token module is stale; run deno task generate:ui-tokens.');
    Deno.exit(1);
  }
  console.log('UI token module sync check passed.');
} else {
  await Deno.writeTextFile(TARGET, generated);
  console.log('Generated packages/ui/src/open-props-tokens.ts from CSS source.');
}
