import { sanitizeHtml, type SanitizeOptions } from '@openelement/element/sanitize';

/** ADR-0126: the single shared allow-list for every Markdown collection. */
export const CONTENT_SANITIZE_OPTIONS: SanitizeOptions = {
  allowedTags: [
    'p',
    'a',
    'code',
    'pre',
    'ul',
    'ol',
    'li',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'blockquote',
    'strong',
    'em',
    'b',
    'i',
    's',
    'del',
    'ins',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    'br',
    'hr',
    'img',
    'figure',
    'figcaption',
    'details',
    'summary',
    'sup',
    'sub',
    'abbr',
    'input',
  ],
  allowedAttributes: {
    '*': ['class', 'id'],
    a: ['href', 'title', 'target', 'rel'],
    img: ['src', 'alt', 'title', 'width', 'height'],
    td: ['colspan', 'rowspan'],
    th: ['colspan', 'rowspan'],
    code: ['language', 'data-language'],
    input: ['type', 'disabled', 'checked'],
    abbr: ['title'],
  },
  allowedSchemes: ['http', 'https', 'mailto', '#', 'relative'],
  disallowedTagsMode: 'discard',
  allowDangerousTags: ['details', 'summary', 'input'],
  linkRel: ['noopener', 'noreferrer'],
  voidElementStyle: 'xhtml',
};

export function sanitizeContentHtml(html: string): string {
  return sanitizeHtml(html, CONTENT_SANITIZE_OPTIONS);
}
